<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <RootNamespace>Jaqueca.Client</RootNamespace>
    <AssemblyName>Jaqueca</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jaqueca.Figures\Jaqueca.Figures.csproj" />
    <ProjectReference Include="..\Jaqueca.Core\Jaqueca.Core.csproj" />
    <ProjectReference Include="..\Jaqueca.Sprites\Jaqueca.Sprites.csproj" />
    <ProjectReference Include="..\Jaqueca.Audio\Jaqueca.Audio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
</Project>
